build:
	g++ -Wall -Wextra -std=c++17 -o poduri poduri.cpp
	g++ -Wall -Wextra -std=c++17 -o adrese adrese.cpp
	g++ -Wall -Wextra -std=c++17 -o lego lego.cpp
	g++ -Wall -Wextra -std=c++17 -o retea retea.cpp

run-p1:
	./poduri

run-p2:
	./adrese

run-p3:
	./lego

run-p4:
	./retea

clean:
	rm poduri, retea, adrese, lego
