build:
	g++ -Wall -Wextra crypto.cpp -o crypto
	
run-p1:
	./crypto

run-p2:
	#TODO

run-p3:
	#TODO

clean: crypto 
	rm crypto

pack:
	zip 322CB_MateescuViorelCristian_Tema1.zip crypto.cpp Makefile README
